### ISSUE TITLE
Print the Conjur cert injection error to the log

### ISSUE THREAD

**Issue by orenbm** [cyberark/conjur-authn-k8s-client#170]
The Conjur server now writes the injection error to a log file in the
client container (https://github.com/cyberark/conjur/pull/1789).

We should print this error to the log to enhance supportability.

**Comment by izgeri** [comment]
just wanted to add some notes about the requirements on this addition, as I understand them:
- this should be backwards compatible, so that if someone uses a new client with an older conjur/DAP the client won't fail
- the log file should be removed when the cert file is removed
- if the log file shows there were errors in the cert injection, those should be logged to the client container stderr as ERROR messages

@orenbm if I've misunderstood any of these requirements, please lmk

**Comment by orenbm** [comment]
You are correct @izgeri .

Regarding the first bullet - the app won't fail but the log will show a WARN message: `CAKC001W File /tmp/conjur_set_file_content.log does no exist`
